# secure_control_protocol
# This is the pubspec file specifying all dependencies
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2020 Benjamin Schilling

name: secure_control_protocol
description: Dart client library for secure-control-protocol devices (see https://github.com/HouseOS/secure-control-protocol)
version: 0.0.10
repository: https://github.com/HouseOS/secure_control_protocol
issue_tracker: https://github.com/HouseOS/secure_control_protocol/issues
documentation: https://github.com/HouseOS/secure_control_protocol/blob/master/README.md
executables: 
  scp_client:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.0
  cryptography: ^2.0.1
  test: ^1.9.1
  collection: ^1.14.12
  convert: ^3.0.0